spring:
  profiles:
    include: local #, private, oauth

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  messages:
    basename: i18n/exception  # "resources/i18n/" path에서 exception_locale.yml을 참조하라는 뜻
    encoding: UTF-8

springdoc:
  packages-to-scan: com.demoproject.demo
  swagger-ui:
    path: demo-ui.html  # # Swagger UI 경로 => localhost:8000/demo-ui.html